language: python

python: "3.4"

before_install:
    - pip install "Sphinx<1.4 commonmark==0.5.5 recommonmark"

script:
    - ".ci/${CI_TARGET}.sh"

env:
    - CI_TARGET=html
    - CI_TARGET=linkcheck

matrix:
    allow_failures:
        - env: CI_TARGET=linkcheck
