language: python

python: "3.4"

before_install:
    - pip install Sphinx commonmark recommonmark

script:
    - ".ci/${CI_TARGET}.sh"

env:
    - CI_TARGET=html
    - CI_TARGET=linkcheck

matrix:
    allow_failures:
        - env: CI_TARGET=linkcheck
